#!/usr/bin/env php
<?php
// phpcs:ignorefile

// ini_set('display_errors', 1);
// error_reporting(-1);

/**
 * Helper functions
 */
function usage($msg = '', $rc = 0)
{
    global $argv;

    $msg && printf("\nERROR - $msg\n");

    printf("\nUsage: " . $argv[0] . " -c <config-file> -t <To: address> -s <subject> [options]\n\n");
    printf("Options:\n");
    printf("\t-c\tConfig file {required}\n");
    printf("\t-t\tTo: address(es) (comma separated) {required}\n");
    printf("\t-s\tSubject {required}\n");
    printf("\t-b\tPlain text body, if starts with @ assume get from file\n");
    printf("\t-f\tHTML body, if starts with @ assume get from file\n");
    printf("\t-w\tCC: address(es) (comma separated)\n");
    printf("\t-z\tBCC: address(es) (comma separated)\n");
    printf("\t-a\tAttachment(s)\n");
    printf("\t-p\tPriority (0|1)\n");
    printf("\t-v[vvv]\tPHPMailer verbosity\n");
    printf("\t-h\tThis help\n\n");
    printf("Possible formats for emails: 'name@example.com' or 'any name <name@example.com>'\n");

    exit($rc);
}

function _die($msg, $rc = 1)
{
    printf("\n::: ERROR $msg\n");
    exit($rc);
}

// --------------------------------------------------------------------------

/**
 * Find composer autoload.php
 */
$autoloads = [
    // Installed via composer
    __DIR__  . '/../../autoload.php',
    // In repo development dir
    __DIR__  . '/vendor/autoload.php'
];

foreach ($autoloads as $autoload) {
    if (is_file($autoload)) {
        require $autoload;
        unset($autoloads);
        break;
    }
}

isset($autoloads) && _die('Missing autoload.php, actual directory is ' . getcwd(), 127);

/**
 * Command line parameters
 */
$options = getopt("hc:t:w:z:s:b:f:a:p:v");

array_key_exists('h', $options) && usage();

$config      = trim($options['c'] ?? '');
$to          = trim($options['t'] ?? '');
$subject     = trim($options['s'] ?? '');
$body        = trim($options['b'] ?? '');
$html        = trim($options['f'] ?? '');
$cc          = trim($options['w'] ?? '');
$bcc         = trim($options['z'] ?? '');
$attachments = $options['a'] ?? null;
$priority    = +($options['p'] ?? 0);
$verbose     = min([count((array) ($options['v'] ?? null)), 4]);

if ($config == '' || $to == '' || $subject == '') {
    usage('Missing required parameter(s)', 1);
}

if ($config && is_file($config)) {
    $config = require $config;
} else {
    _die('Missing config file, actual directory is ' . getcwd(), 1);
}

// SMTP needs accurate times, and the PHP time zone MUST be set
// This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set($config['timezone'] ?? 'UTC');

/**
 * Create a PHPMailer instance
 */
$mail = new \PHPMailer\PHPMailer\PHPMailer();

$mail->XMailer    = null;       // Suppress X-Mailer header
$mail->CharSet    = 'UTF-8';
$mail->Encoding   = 'base64';
$mail->AllowEmpty = true;       // Body may be empty, e.g. for status emails
$mail->SMTPDebug  = $verbose;   // Enable SMTP debugging, -v ... -vvvv

if (!($config['verify-peer'] ?? true)){
    $mail->SMTPOptions = [
        'ssl' => [
            'verify_peer' => false,
            'verify_peer_name' => false,
            'allow_self_signed' => true
        ]
    ];
}

// Tell PHPMailer to use SMTP
$mail->isSMTP();

// Set the hostname and port of the mail server
$mail->Host = $config['host'] ?? '';
$mail->Port = $config['port'] ?? 25; # likely to be 25, 465 or 587

// Whether to use SMTP authentication
$mail->SMTPAuth = true;

// Username and password to use for SMTP authentication
$mail->Username = $config['user'] ?? '';
$mail->Password = $config['pass'] ?? '';

// Set who the message is to be sent from
if (isset($config['from'])) {
    if (preg_match('~^(.+) *<(.+?)>~', $config['from'], $args)) {
        $mail->setFrom($args[2], $args[1]);
    } else {
        $mail->setFrom($config['from']);
    }
}

// To: 'name@example.com' or 'any name <name@example.com>'
foreach ($to ? explode(',', $to) : [] as $addr) {
    if (preg_match('~^(.+) *<(.+?)>~', $addr, $args)) {
        $mail->addAddress($args[2], trim($args[1]));
    } else {
        $mail->addAddress($addr);
    }
}

// CC: 'name@example.com' or 'any name <name@example.com>'
foreach ($cc ? explode(',', $cc) : [] as $addr) {
    if (preg_match('~^(.+) *<(.+?)>~', $addr, $args)) {
        $mail->addCC($args[2], trim($args[1]));
    } else {
        $mail->addCC($addr);
    }
}

// BCC: 'name@example.com' or 'any name <name@example.com>'
foreach ($bcc ? explode(',', $bcc) : [] as $addr) {
    if (preg_match('~^(.+) *<(.+?)>~', $addr, $args)) {
        $mail->addBCC($args[2], trim($args[1]));
    } else {
        $mail->addBCC($addr);
    }
}

// Encode the subject line to UTF-8
$mail->Subject = '=?UTF-8?B?' . base64_encode($subject) . '?=';

// 1st use HTML body
if (!empty($html)) {
    if (substr($html, 0, 1) === '@') {
        $html = substr($html, 1);
        is_file($html) || _die('Missing HTML body file: ' . $html, 2);
        $html = file_get_contents($html);
    }

    $mail->Body = $html;
    $mail->isHTML(true);
} else {
    if (substr($body, 0, 1) === '@') {
        $body = substr($body, 1);
        is_file($body) || _die('Missing message body file: ' . $body, 3);
        $body = file_get_contents($body);
    }

    $mail->Body = $body;
    $mail->WordWrap = 72;
}

// Attachments
foreach ((array) $attachments as $attachment) {
    is_file($html) || _die('Missing attachment: ' . $attachment, 4);
    $mail->addAttachment($attachment);
}

if ($priority) {
    // https://stackoverflow.com/a/10766851
    // For most clients expecting the Priority header:
    // 1 = High, 2 = Medium, 3 = Low
    $mail->Priority = 1;
    // MS Outlook custom header
    // May set to "Urgent" or "Highest" rather than "High"
    $mail->AddCustomHeader('X-MSMail-Priority: High');
}

// Send the message, check for errors
if (!$mail->send()) {
    fwrite(STDERR, $mail->ErrorInfo . PHP_EOL);
    exit(127);
}
